idf_component_register(
    SRCS 
	"ADC/ADC.cpp"
	"ADC/MonitorVoltageThresholdHandle.cpp"
	"ADC/ReverseVoltageToRawLookup.cpp"
	"cJSON/cJSON.c"
	"Communication/FiberOptic/TOSLINKDuplexChannel.cpp"
	"Communication/UART/UARTDuplexChannel.cpp"
	"Communication/Bluetooth/Bluetooth_BR_EDR.cpp" 
	"Communication/I2C/I2C.cpp"
	"Communication/I2C/I2CConfiguration.cpp"
	"Components/TemperatureSensors/LM75A.cpp" 
	"Components/Accelerometers/MPU6050.cpp" 
	"Core/CancellationToken.cpp"
	"Core/Checksums/Crc32.cpp"
	"JSON/CJsonRAII.cpp"
	"Core/CleanupBucket.cpp"
	"Core/Latch.cpp"
	"Core/RefCounted.cpp"
	"Core/Timer.cpp"
	"Core/TimerSimple.cpp"
	"JSON/JHelper.cpp"
	"Logging/Log.cpp"
	"Storage/Flash.cpp"
	"System/WatchdogFeeder.cpp"
	"System/StayTheFuckAwake.cpp"
	"Ticketing/TicketedSender.cpp"
	"Ticketing/TicketedSenderHandle.cpp"
	"Ticketing/TicketSource.cpp"
	"Timing/Delay.cpp"
	"Timing/TimeHelper.cpp"
	"Generated/Messages/ConsoleMessage.cpp"
	"Generated/Messages/GetVoltageRequest.cpp"
	"Generated/Messages/GetVoltageResponse.cpp"
	"Generated/Messages/HVPSStateChangedMessage.cpp"
	"Generated/Messages/HVPSLiveDataMessage.cpp"
	"Generated/Messages/HVPSRunSystemChecksOnlyMessage.cpp"
	"Generated/Messages/HVPSStartMessage.cpp"
	"Generated/Messages/HVPSStopMessage.cpp"
	"Generated/Messages/HVPSShutDownMessage.cpp"
	"Generated/Messages/PingMessage.cpp"
	"Generated/Messages/SetVoltageThresholdRequest.cpp"
	"Generated/Messages/SetVoltageThresholdResponse.cpp"
	"Generated/Messages/VoltageMessage.cpp"
    PRIV_REQUIRES spi_flash driver bt nvs_flash esp_adc
    INCLUDE_DIRS
        .       # lets you #include "Core/Event.hpp" or "Utils/Foo.hpp"
)
