M48
; DRILL file {KiCad 8.0.8} date 2025-05-01T12:37:28+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-01T12:37:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X22.3Y-17.0
X24.7Y-17.0
X27.2Y-17.0
X29.6Y-17.0
T2
X19.0Y-18.0
X33.0Y-18.0
M30
