<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\shared-private\Configuration\Configurations.csproj" />
    <ProjectReference Include="..\..\..\..\shared-public\BaseMessages\CSharp\BaseMessages.csproj" />
    <ProjectReference Include="..\..\..\..\shared-public\DataMemberNamesClassBuilder\DataMemberNamesClassBuilder.csproj" />
    <ProjectReference Include="..\..\..\..\shared-public\Bluetooth\CSharp\Bluetooth.csproj" />
    <ProjectReference Include="..\..\..\..\shared-public\Native\CSharp\Native.csproj" />
    <ProjectReference Include="..\HVPSAPI\HVPSAPI.csproj" />
    <ProjectReference Include="..\HVPSMessages\HVPSMessages.csproj" />
    <ProjectReference Include="..\HVPSUIMessages\HVPSUIMessages.csproj" />
    <ProjectReference Include="..\VoltageFeedbackMessages\VoltageFeedbackMessages.csproj" />
  </ItemGroup>
</Project>