#include "PinDefinitions.hpp"
#include "driver/gpio.h"
int PinDefinitions::OUTPUT_VOLTAGE_FEEDBACK_RX = GPIO_NUM_4;
int PinDefinitions::OUTPUT_VOLTAGE_FEEDBACK_TX = GPIO_NUM_17;
int PinDefinitions::OUTPUT_VOLTAGE_FEEDBACK_THRESHOLD_REACHED = GPIO_NUM_32;
int PinDefinitions::FIRST_STAGE_VOLTAGE_FEEDBACK_RX = GPIO_NUM_18;
int PinDefinitions::FIRST_STAGE_VOLTAGE_FEEDBACK_TX = GPIO_NUM_19;
int PinDefinitions::FIRST_STAGE_VOLTAGE_FEEDBACK_THRESHOLD_REACHED = GPIO_NUM_5;
int PinDefinitions::OUTPUT_CURRENT_FEEDBACK_TX = GPIO_NUM_33;
int PinDefinitions::OUTPUT_CURRENT_FEEDBACK_RX = GPIO_NUM_25;
int PinDefinitions::OUTPUT_CURRENT_FEEDBACK_THRESHOLD_REACHED = GPIO_NUM_26;
int PinDefinitions::PERIPHERALS_TX = GPIO_NUM_27;
int PinDefinitions::PERIPHERALS_RX = GPIO_NUM_14;
int PinDefinitions::MOSFET_DRIVE = GPIO_NUM_23;
int PinDefinitions::PRIMARY_CURRENT_FEEDBACK = GPIO_NUM_34;
int PinDefinitions::POWER_SUPPLY_VOLTAGE_FEEDBACK = GPIO_NUM_35;
int PinDefinitions::SNUBBER_VOLTAGE_FEEDBACK = GPIO_NUM_36;
int PinDefinitions::REFERENCE_VOLTAGE = GPIO_NUM_39;